RunType.create(type: "Clean")
RunType.create(type: "Dirty")
RunType.create(type: "Ground")
Flock.create(name: "Flock 1")
Flock.create(name: "Flock 2")
Flock.create(name: "Flock 3")
Flock.create(name: "Flock 4")
