TrayType.create(type: "Clean")
TrayType.create(type: "Dirty")
TrayType.create(type: "Ground")
Shed.create(name: "Shed 1")
Shed.create(name: "Shed 2")
Shed.create(name: "Shed 3")
Shed.create(name: "Shed 4")
